from .extreme_parkour_terrains_cfg import (
ExtremeParkourRoughTerrainCfg,
ExtremeParkourGapTerrainCfg,
ExtremeParkourHurdleTerrainCfg,
ExtremeParkourStepTerrainCfg,
ExtremeParkourBeamTerrainCfg,
ExtremeParkourTerrainCfg,
ExtremeParkourDemoTerrainCfg
)
